import { Product, ProductCategory, Brand, CarouselSlide } from '../types';

export const INITIAL_CATEGORIES: ProductCategory[] = [
  {
    id: 'cat-screens-tvs',
    name_ar: 'الشاشات والتلفزيونات',
    name_en: 'Screens & TVs',
    name: 'الشاشات والتلفزيونات',
    slug: 'screens-tvs',
    icon_name: 'Tv',
    sort_order: 1,
    is_featured: true,
    is_active: true,
    product_count: 2,
  },
  {
    id: 'cat-security-cameras',
    name_ar: 'كاميرات المراقبة والأنظمة الأمنية',
    name_en: 'Security & CCTV Cameras',
    name: 'كاميرات المراقبة والأنظمة الأمنية',
    slug: 'security-cameras',
    icon_name: 'Camera',
    sort_order: 2,
    is_featured: true,
    is_active: true,
    product_count: 2,
  },
  {
    id: 'cat-dvr-nvr',
    name_ar: 'أجهزة التسجيل DVR & NVR',
    name_en: 'DVR & NVR Systems',
    name: 'أجهزة التسجيل DVR & NVR',
    slug: 'dvr-nvr-systems',
    icon_name: 'HardDrive',
    sort_order: 3,
    is_featured: true,
    is_active: true,
    product_count: 2,
  },
  {
    id: 'cat-networking',
    name_ar: 'الشبكات والراوترات والمحولات',
    name_en: 'Networking, Routers & Switches',
    name: 'الشبكات والراوترات والمحولات',
    slug: 'networking-routers',
    icon_name: 'Wifi',
    sort_order: 4,
    is_featured: true,
    is_active: true,
    product_count: 2,
  },
  {
    id: 'cat-cables-power',
    name_ar: 'الكابلات ومزودات الطاقة والملحقات',
    name_en: 'Cables, Power Supplies & Accessories',
    name: 'الكابلات ومزودات الطاقة والملحقات',
    slug: 'cables-power',
    icon_name: 'Zap',
    sort_order: 5,
    is_featured: true,
    is_active: true,
    product_count: 2,
  },
];

export const INITIAL_BRANDS: Brand[] = [
  { id: 'brand-hikvision', name: 'Hikvision', slug: 'hikvision', is_active: true },
  { id: 'brand-dahua', name: 'Dahua', slug: 'dahua', is_active: true },
  { id: 'brand-samsung', name: 'Samsung', slug: 'samsung', is_active: true },
  { id: 'brand-lg', name: 'LG', slug: 'lg', is_active: true },
  { id: 'brand-tplink', name: 'TP-Link', slug: 'tp-link', is_active: true },
  { id: 'brand-cisco', name: 'Cisco', slug: 'cisco', is_active: true },
];

export const INITIAL_SLIDES: CarouselSlide[] = [
  {
    id: 'slide-1',
    title_ar: 'أقوى عروض أنظمة المراقبة والكاميرات الذكية',
    subtitle_ar: 'كاميرات 4K ملونة ليلية من هيكفيجن وداهوا مع إشراف وتركيب هندسي معتمد',
    image_url: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=1600&q=85',
    button_text_ar: 'تصفح كاميرات المراقبة',
    link_url: '/products',
    category_id: 'cat-security-cameras',
    category_name_ar: 'كاميرات المراقبة',
    sort_order: 1,
    is_active: true,
  },
  {
    id: 'slide-2',
    title_ar: 'أحدث الشاشات الذكية 4K UHD لعام 2026',
    subtitle_ar: 'شاشات سامسونج وإل جي الأصلية بضمان رسمي وأسعار منافسة مع شحن لكافة المحافظات',
    image_url: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=1600&q=85',
    button_text_ar: 'استكشف الشاشات',
    link_url: '/products',
    category_id: 'cat-screens-tvs',
    category_name_ar: 'الشاشات والتلفزيونات',
    sort_order: 2,
    is_active: true,
  },
  {
    id: 'slide-3',
    title_ar: 'حلول الشبكات والراوترات فائقة السرعة WiFi 6',
    subtitle_ar: 'راوترات ومقويات إشارة وسويتشات سيسكو وتي بي لينك لتغطية شاملة وثابتة',
    image_url: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=1600&q=85',
    button_text_ar: 'تصفح أجهزة الشبكات',
    link_url: '/products',
    category_id: 'cat-networking',
    category_name_ar: 'أجهزة الشبكات',
    sort_order: 3,
    is_active: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-hik-5mp-cv',
    category_id: 'cat-security-cameras',
    category_slug: 'security-cameras',
    category_name_ar: 'كاميرات المراقبة والأنظمة الأمنية',
    brand_id: 'brand-hikvision',
    brand_name: 'Hikvision',
    name_ar: 'كاميرا مراقبة هيكفيجن 5 ميجابكسل رؤية ليلية ملونة ColorVu مع مايك',
    name_en: 'Hikvision 5MP ColorVu Audio Fixed Mini Bullet Camera',
    name: 'كاميرا مراقبة هيكفيجن 5 ميجابكسل رؤية ليلية ملونة ColorVu مع مايك',
    sku: 'HIK-5MP-CV-01',
    description_ar: 'كاميرا مراقبة خارجية فائقة الوضوح بدقة 5 ميجابكسل، تدعم التصوير الليلي الملون 24/7 مع مايكروفون مدمج عالي الحساسية لنقل الصوت وهيكل معدني مقاوم للعوامل الجوية بمعيار IP67.',
    image_url: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80',
    main_image_url: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80',
    pricing_mode: 'USD_LINKED',
    base_cost: 35.0,
    base_currency: 'USD',
    profit_margin_percent: 18.0,
    manual_egp_price: 2190.0,
    old_price: 2450.0,
    discount_percent: 10.0,
    stock_quantity: 25,
    low_stock_threshold: 5,
    is_available: true,
    is_featured: true,
    is_active: true,
    specifications: {
      'الدقة': '5 ميجابكسل (2560x1944)',
      'الرؤية الليلية': 'تصوير ملون على مدار الساعة 24/7 حتى 30 متر',
      'مقاومة الماء': 'معيار IP67 مقاوم للأمطار والأتربة',
      'الصوت': 'ميكروفون مدمج عالي النقاء',
      'العدسة': '2.8 مم زاوية رؤية واسعة 105 درجة',
    },
    warranty_info: 'ضمان سنتين معتمد من الوكيل الرسمي وباش مهندس أحمد السيد',
    created_at: new Date().toISOString(),
    pricing: {
      sellingPriceEgp: 2190.0,
      calculatedBaseEgp: 2450.0,
      oldPriceEgp: 2450.0,
      discountPercent: 10.0,
      pricingMode: 'USD_LINKED',
      baseCost: 35.0,
      baseCurrency: 'USD',
      profitMarginPercent: 18.0,
      effectiveRate: 50.0,
    },
  },
  {
    id: 'prod-dh-xvr-8ch-4k',
    category_id: 'cat-dvr-nvr',
    category_slug: 'dvr-nvr-systems',
    category_name_ar: 'أجهزة التسجيل DVR & NVR',
    brand_id: 'brand-dahua',
    brand_name: 'Dahua',
    name_ar: 'جهاز تسجيل داهوا XVR 8 قنوات 4K بتقنية الذكاء الاصطناعي WizSense',
    name_en: 'Dahua 8 Channel WizSense 4K XVR Digital Video Recorder',
    name: 'جهاز تسجيل داهوا XVR 8 قنوات 4K بتقنية الذكاء الاصطناعي WizSense',
    sku: 'DH-XVR-8CH-4K',
    description_ar: 'جهاز تسجيل فيديو احترافي 8 قنوات يدعم كاميرات حتى دقة 8 ميجابكسل (4K)، مزود بتقنيات الذكاء الاصطناعي لكشف الأشخاص والمركبات بدقة مع ضغط فيديو H.265+ ومخارج HDMI 4K.',
    image_url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
    main_image_url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
    pricing_mode: 'USD_LINKED',
    base_cost: 75.0,
    base_currency: 'USD',
    profit_margin_percent: 15.0,
    manual_egp_price: 4650.0,
    old_price: 5100.0,
    discount_percent: 9.0,
    stock_quantity: 12,
    low_stock_threshold: 3,
    is_available: true,
    is_featured: true,
    is_active: true,
    specifications: {
      'عدد القنوات': '8 قنوات فيديو تناظري + قنوات IP إضافية',
      'أقصى دقة تسجيل': '4K Ultra HD (3840x2160)',
      'الذكاء الاصطناعي': 'كشف ذكي وتصنيف دقيق للأشخاص والسيارات WizSense',
      'سعة الهارد': 'يدعم قرص صلب حتى 10 تيرابايت SATA',
      'المنافذ': 'HDMI 4K, VGA, LAN, 2x USB, Audio In/Out',
    },
    warranty_info: 'ضمان 24 شهراً مع دعم فني وبرمجة مجانية من باش مهندس أحمد السيد',
    created_at: new Date().toISOString(),
    pricing: {
      sellingPriceEgp: 4650.0,
      calculatedBaseEgp: 5100.0,
      oldPriceEgp: 5100.0,
      discountPercent: 9.0,
      pricingMode: 'USD_LINKED',
      baseCost: 75.0,
      baseCurrency: 'USD',
      profitMarginPercent: 15.0,
      effectiveRate: 50.0,
    },
  },
  {
    id: 'prod-sam-tv-55-4k',
    category_id: 'cat-screens-tvs',
    category_slug: 'screens-tvs',
    category_name_ar: 'الشاشات والتلفزيونات',
    brand_id: 'brand-samsung',
    brand_name: 'Samsung',
    name_ar: 'شاشة سامسونج سمارت 55 بوصة بدقة 4K UHD مع ريسيفر داخلي معالج Crystal 4K',
    name_en: 'Samsung 55 Inch 4K UHD Smart TV Crystal Processor Built-in Receiver',
    name: 'شاشة سامسونج سمارت 55 بوصة بدقة 4K UHD مع ريسيفر داخلي معالج Crystal 4K',
    sku: 'SAM-TV-55-CU7000',
    description_ar: 'شاشة سامسونج الأصلية 55 بوصة بدقة 4K فائقة الوضوح مع معالج Crystal Processor 4K لتدرج ألوان سينمائي، نظام تشغيل Tizen الذكي، دعم نتفلكس ويوتيوب وريسيفر فضائي داخلي.',
    image_url: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80',
    main_image_url: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80',
    pricing_mode: 'FIXED_EGP',
    base_cost: 16500.0,
    base_currency: 'EGP',
    profit_margin_percent: 10.0,
    manual_egp_price: 18900.0,
    old_price: 20500.0,
    discount_percent: 8.0,
    stock_quantity: 8,
    low_stock_threshold: 2,
    is_available: true,
    is_featured: true,
    is_active: true,
    specifications: {
      'حجم الشاشة': '55 بوصة بدون حواف (Bezel-less)',
      'الدقة': '3840x2160 Ultra HD 4K',
      'المعالج': 'Crystal Processor 4K ذكي',
      'النظام': 'Tizen Smart TV مع دعم المساعد الصوتي والتحكم من الهاتف',
      'الاتصال': '3x HDMI, 1x USB, Wi-Fi 5, Bluetooth, LAN',
    },
    warranty_info: 'ضمان سنتين رسمي معتمد من العربي جروب وسامسونج مصر',
    created_at: new Date().toISOString(),
    pricing: {
      sellingPriceEgp: 18900.0,
      calculatedBaseEgp: 20500.0,
      oldPriceEgp: 20500.0,
      discountPercent: 8.0,
      pricingMode: 'FIXED_EGP',
      baseCost: 16500.0,
      baseCurrency: 'EGP',
      profitMarginPercent: 10.0,
      effectiveRate: 1.0,
    },
  },
  {
    id: 'prod-tplink-ax53-wifi6',
    category_id: 'cat-networking',
    category_slug: 'networking-routers',
    category_name_ar: 'الشبكات والراوترات والمحولات',
    brand_id: 'brand-tplink',
    brand_name: 'TP-Link',
    name_ar: 'راوتر تي بي لينك آرتشر AX53 جيجابت واي فاي 6 سرعة 3000 ميجابت',
    name_en: 'TP-Link Archer AX53 AX3000 Dual-Band Gigabit Wi-Fi 6 Router',
    name: 'راوتر تي بي لينك آرتشر AX53 جيجابت واي فاي 6 سرعة 3000 ميجابت',
    sku: 'TPL-ARCHER-AX53',
    description_ar: 'راوتر الجيل التالي بتقنية Wi-Fi 6 بسرعات تصل إلى 3000 ميجابت/ثانية (2402 ميجابت على 5 جيجاهرتز + 574 ميجابت على 2.4 جيجاهرتز)، مزود بـ 4 هوائيات عالية الكسب ومنافذ جيجابت كاملة.',
    image_url: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80',
    main_image_url: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80',
    pricing_mode: 'USD_LINKED',
    base_cost: 48.0,
    base_currency: 'USD',
    profit_margin_percent: 16.0,
    manual_egp_price: 2950.0,
    old_price: 3300.0,
    discount_percent: 11.0,
    stock_quantity: 18,
    low_stock_threshold: 4,
    is_available: true,
    is_featured: true,
    is_active: true,
    specifications: {
      'السرعة القصوى': 'AX3000 (2402 Mbps 5GHz + 574 Mbps 2.4GHz)',
      'التقنية': 'WiFi 6 مع OFDMA و MU-MIMO و Beamforming',
      'المنافذ': '1x Gigabit WAN + 4x Gigabit LAN',
      'الأمان': 'WPA3 المتقدم مع بروتوكول HomeShield للحماية من الاختراق',
    },
    warranty_info: 'ضمان استبدال معتمد سنة كاملة',
    created_at: new Date().toISOString(),
    pricing: {
      sellingPriceEgp: 2950.0,
      calculatedBaseEgp: 3300.0,
      oldPriceEgp: 3300.0,
      discountPercent: 11.0,
      pricingMode: 'USD_LINKED',
      baseCost: 48.0,
      baseCurrency: 'USD',
      profitMarginPercent: 16.0,
      effectiveRate: 50.0,
    },
  },
  {
    id: 'prod-lg-tv-65-uhd',
    category_id: 'cat-screens-tvs',
    category_slug: 'screens-tvs',
    category_name_ar: 'الشاشات والتلفزيونات',
    brand_id: 'brand-lg',
    brand_name: 'LG',
    name_ar: 'شاشة إل جي سمارت 65 بوصة 4K UHD مع ريموت ماجيك ذكي ونظام webOS',
    name_en: 'LG 65 Inch 4K UHD Smart TV with Magic Remote webOS',
    name: 'شاشة إل جي سمارت 65 بوصة 4K UHD مع ريموت ماجيك ذكي ونظام webOS',
    sku: 'LG-TV-65-UR8000',
    description_ar: 'تلفزيون إل جي الذكي 65 بوصة بتجربة سينمائية فائقة بدقة 4K Real UHD مع ريموت التحكم السحري Magic Remote ومعالج α5 AI Processor Gen6 وذكاء ThinQ AI.',
    image_url: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80',
    main_image_url: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=80',
    pricing_mode: 'FIXED_EGP',
    base_cost: 23500.0,
    base_currency: 'EGP',
    profit_margin_percent: 9.0,
    manual_egp_price: 26900.0,
    old_price: 28900.0,
    discount_percent: 7.0,
    stock_quantity: 6,
    low_stock_threshold: 2,
    is_available: true,
    is_featured: true,
    is_active: true,
    specifications: {
      'حجم الشاشة': '65 بوصة Real 4K UHD',
      'المعالج': 'معالج α5 AI 4K الجيل السادس',
      'الصوت': 'AI Sound مع تحسين الصوت الافتراضي 5.1.2',
      'الريموت': 'Magic Remote الماوس الهوائي الذكي',
      'المنافذ': '3x HDMI 2.0 (eARC), 2x USB, Optical, LAN, Bluetooth 5.0',
    },
    warranty_info: 'ضمان سنتين شامل الوكيل الرسمي لإل جي في مصر',
    created_at: new Date().toISOString(),
    pricing: {
      sellingPriceEgp: 26900.0,
      calculatedBaseEgp: 28900.0,
      oldPriceEgp: 28900.0,
      discountPercent: 7.0,
      pricingMode: 'FIXED_EGP',
      baseCost: 23500.0,
      baseCurrency: 'EGP',
      profitMarginPercent: 9.0,
      effectiveRate: 1.0,
    },
  },
  {
    id: 'prod-hik-ip-4mp-dome',
    category_id: 'cat-security-cameras',
    category_slug: 'security-cameras',
    category_name_ar: 'كاميرات المراقبة والأنظمة الأمنية',
    brand_id: 'brand-hikvision',
    brand_name: 'Hikvision',
    name_ar: 'كاميرا مراقبة هيكفيجن IP دوم 4 ميجابكسل PoE داخلية وخارجية مع مايك',
    name_en: 'Hikvision 4MP IP PoE Audio Dome Security Camera',
    name: 'كاميرا مراقبة هيكفيجن IP دوم 4 ميجابكسل PoE داخلية وخارجية مع مايك',
    sku: 'HIK-IP-4MP-DM',
    description_ar: 'كاميرا شبكية IP دوم بدقة 4 ميجابكسل تدعم التغذية عبر كابل الشبكة PoE مع رؤية ليلية بالأشعة تحت الحمراء حتى 30 متر، مايك داخلي، ودعم معيار الحماية ضد الصدمات IK10 والطقس IP67.',
    image_url: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80',
    main_image_url: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80',
    pricing_mode: 'USD_LINKED',
    base_cost: 42.0,
    base_currency: 'USD',
    profit_margin_percent: 18.0,
    manual_egp_price: 2590.0,
    old_price: 2850.0,
    discount_percent: 9.0,
    stock_quantity: 30,
    low_stock_threshold: 6,
    is_available: true,
    is_featured: true,
    is_active: true,
    specifications: {
      'الدقة': '4 ميجابكسل (2560x1440 @ 25fps)',
      'التغذية': 'PoE (802.3af) أو 12V DC',
      'ضغط الفيديو': 'H.265+ فائق التوفير',
      'المتانة': 'IK10 ضد التخريب و IP67 ضد المياه والأتربة',
    },
    warranty_info: 'ضمان معتمد سنتين من باش مهندس أحمد السيد',
    created_at: new Date().toISOString(),
    pricing: {
      sellingPriceEgp: 2590.0,
      calculatedBaseEgp: 2850.0,
      oldPriceEgp: 2850.0,
      discountPercent: 9.0,
      pricingMode: 'USD_LINKED',
      baseCost: 42.0,
      baseCurrency: 'USD',
      profitMarginPercent: 18.0,
      effectiveRate: 50.0,
    },
  },
  {
    id: 'prod-cisco-sg110-switch',
    category_id: 'cat-networking',
    category_slug: 'networking-routers',
    category_name_ar: 'الشبكات والراوترات والمحولات',
    brand_id: 'brand-cisco',
    brand_name: 'Cisco',
    name_ar: 'سويتش شبكات سيسكو 8 منافذ جيجابت Cisco CBS110 Unmanaged Switch',
    name_en: 'Cisco CBS110 8-Port Gigabit Desktop Unmanaged Switch',
    name: 'سويتش شبكات سيسكو 8 منافذ جيجابت Cisco CBS110 Unmanaged Switch',
    sku: 'CISCO-CBS110-8T',
    description_ar: 'محول شبكة مكتبي عالي الاعتمادية من سيسكو بـ 8 منافذ سرعة 10/100/1000 جيجابت، تصميم معدني متين بدون مراوح لتشغيل صامت مع توفير استهلاك الطاقة.',
    image_url: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80',
    main_image_url: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80',
    pricing_mode: 'USD_LINKED',
    base_cost: 32.0,
    base_currency: 'USD',
    profit_margin_percent: 15.0,
    manual_egp_price: 1980.0,
    old_price: 2200.0,
    discount_percent: 10.0,
    stock_quantity: 15,
    low_stock_threshold: 3,
    is_available: true,
    is_featured: true,
    is_active: true,
    specifications: {
      'عدد المنافذ': '8 منافذ Gigabit RJ-45',
      'السرعة': '10/100/1000 Mbps Auto MDI/MDIX',
      'الهيكل': 'معدني كامل بدون مراوح (Fanless)',
      'الاعتمادية': 'جودة سيسكو للمؤسسات والأعمال',
    },
    warranty_info: 'ضمان استبدال رسمي لمدة سنتين',
    created_at: new Date().toISOString(),
    pricing: {
      sellingPriceEgp: 1980.0,
      calculatedBaseEgp: 2200.0,
      oldPriceEgp: 2200.0,
      discountPercent: 10.0,
      pricingMode: 'USD_LINKED',
      baseCost: 32.0,
      baseCurrency: 'USD',
      profitMarginPercent: 15.0,
      effectiveRate: 50.0,
    },
  },
  {
    id: 'prod-cat6-cable-roll',
    category_id: 'cat-cables-power',
    category_slug: 'cables-power',
    category_name_ar: 'الكابلات ومزودات الطاقة والملحقات',
    brand_id: 'brand-dahua',
    brand_name: 'Dahua',
    name_ar: 'لفة كابل شبكة Cat6 نحاس نقي 100% طول 305 متر لنقل البيانات وكاميرات IP',
    name_en: 'Dahua 305M Pure Copper Cat6 UTP Network Cable Roll',
    name: 'لفة كابل شبكة Cat6 نحاس نقي 100% طول 305 متر لنقل البيانات وكاميرات IP',
    sku: 'DH-CAT6-305M-CU',
    description_ar: 'لفة سلك شبكة UTP Cat6 نحاس نقي خام 100% مخصصة لأعلى سرعات نقل البيانات وأنظمة كاميرات المراقبة الشبكية لمسافات طويلة دون فقد في الإشارة أو الجهد الكهربائي.',
    image_url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
    main_image_url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
    pricing_mode: 'USD_LINKED',
    base_cost: 45.0,
    base_currency: 'USD',
    profit_margin_percent: 14.0,
    manual_egp_price: 2750.0,
    old_price: 3000.0,
    discount_percent: 8.0,
    stock_quantity: 20,
    low_stock_threshold: 4,
    is_available: true,
    is_featured: true,
    is_active: true,
    specifications: {
      'نوع السلك': 'Cat6 UTP 4 Pairs',
      'الخامة': 'نحاس نقي 100% (Solid Bare Copper 0.53mm)',
      'الطول': '305 متر (1000 قدم)',
      'الاستخدام': 'راوترات، سويتشات، أنظمة كاميرات IP PoE وشبكات المؤسسات',
    },
    warranty_info: 'ضمان الجودة الأصلية واختبار الفلوك Fluke Test معتمد',
    created_at: new Date().toISOString(),
    pricing: {
      sellingPriceEgp: 2750.0,
      calculatedBaseEgp: 3000.0,
      oldPriceEgp: 3000.0,
      discountPercent: 8.0,
      pricingMode: 'USD_LINKED',
      baseCost: 45.0,
      baseCurrency: 'USD',
      profitMarginPercent: 14.0,
      effectiveRate: 50.0,
    },
  },
];
