/**
 * Controlled System Status Enums for Hyper Technology Store
 */

export enum OrderStatus {
  PENDING = 'PENDING',
  PAYMENT_VERIFICATION = 'PAYMENT_VERIFICATION',
  CONFIRMED = 'CONFIRMED',
  PROCESSING = 'PROCESSING',
  READY = 'READY',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_VERIFICATION = 'PAYMENT_VERIFICATION',
  PAID = 'PAID',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
  REFUNDED = 'REFUNDED',
}

export enum PaymentMethod {
  CASH_ON_DELIVERY = 'CASH_ON_DELIVERY',
  INSTAPAY = 'INSTAPAY',
  VODAFONE_CASH = 'VODAFONE_CASH',
}

export enum PricingMode {
  FIXED_EGP = 'FIXED_EGP',
  USD_LINKED = 'USD_LINKED',
}
